// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "AlprService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::ThriftAlpr;

class AlprServiceHandler : virtual public AlprServiceIf {
 public:
  AlprServiceHandler() {
    // Your initialization goes here
  }

  void getVersion(std::string& _return) {
    // Alpr Implementation
      _return = Alpr::getVersion();
  }

};

int main(int argc, char **argv) {
    std::cout << "Starting Thrift Server on port 9090..." << std::endl;
  int port = 9090;
  shared_ptr<AlprServiceHandler> handler(new AlprServiceHandler());
  shared_ptr<TProcessor> processor(new AlprServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

