/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef AlprService_H
#define AlprService_H

#include <thrift/TDispatchProcessor.h>
#include "thriftalpr_types.h"
#include "alpr.h"

namespace ThriftAlpr {

class AlprServiceIf {
 public:
  virtual ~AlprServiceIf() {}
  virtual void getVersion(std::string& _return) = 0;
};

class AlprServiceIfFactory {
 public:
  typedef AlprServiceIf Handler;

  virtual ~AlprServiceIfFactory() {}

  virtual AlprServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(AlprServiceIf* /* handler */) = 0;
};

class AlprServiceIfSingletonFactory : virtual public AlprServiceIfFactory {
 public:
  AlprServiceIfSingletonFactory(const boost::shared_ptr<AlprServiceIf>& iface) : iface_(iface) {}
  virtual ~AlprServiceIfSingletonFactory() {}

  virtual AlprServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(AlprServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<AlprServiceIf> iface_;
};

class AlprServiceNull : virtual public AlprServiceIf {
 public:
  virtual ~AlprServiceNull() {}
  void getVersion(std::string& /* _return */) {
    return;
  }
};


class AlprService_getVersion_args {
 public:

  AlprService_getVersion_args() {
  }

  virtual ~AlprService_getVersion_args() throw() {}


  bool operator == (const AlprService_getVersion_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const AlprService_getVersion_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const AlprService_getVersion_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class AlprService_getVersion_pargs {
 public:


  virtual ~AlprService_getVersion_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _AlprService_getVersion_result__isset {
  _AlprService_getVersion_result__isset() : success(false) {}
  bool success;
} _AlprService_getVersion_result__isset;

class AlprService_getVersion_result {
 public:

  AlprService_getVersion_result() : success() {
  }

  virtual ~AlprService_getVersion_result() throw() {}

  std::string success;

  _AlprService_getVersion_result__isset __isset;

  void __set_success(const std::string& val) {
    success = val;
  }

  bool operator == (const AlprService_getVersion_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const AlprService_getVersion_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const AlprService_getVersion_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _AlprService_getVersion_presult__isset {
  _AlprService_getVersion_presult__isset() : success(false) {}
  bool success;
} _AlprService_getVersion_presult__isset;

class AlprService_getVersion_presult {
 public:


  virtual ~AlprService_getVersion_presult() throw() {}

  std::string* success;

  _AlprService_getVersion_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class AlprServiceClient : virtual public AlprServiceIf {
 public:
  AlprServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  AlprServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getVersion(std::string& _return);
  void send_getVersion();
  void recv_getVersion(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class AlprServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<AlprServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (AlprServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_getVersion(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  AlprServiceProcessor(boost::shared_ptr<AlprServiceIf> iface) :
    iface_(iface) {
    processMap_["getVersion"] = &AlprServiceProcessor::process_getVersion;
  }

  virtual ~AlprServiceProcessor() {}
};

class AlprServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  AlprServiceProcessorFactory(const ::boost::shared_ptr< AlprServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< AlprServiceIfFactory > handlerFactory_;
};

class AlprServiceMultiface : virtual public AlprServiceIf {
 public:
  AlprServiceMultiface(std::vector<boost::shared_ptr<AlprServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~AlprServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<AlprServiceIf> > ifaces_;
  AlprServiceMultiface() {}
  void add(boost::shared_ptr<AlprServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void getVersion(std::string& _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getVersion(_return);
    }
    ifaces_[i]->getVersion(_return);
    return;
  }

};

} // namespace

#endif
