/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef thriftalpr_CONSTANTS_H
#define thriftalpr_CONSTANTS_H

#include "thriftalpr_types.h"

namespace ThriftAlpr {

class thriftalprConstants {
 public:
  thriftalprConstants();

};

extern const thriftalprConstants g_thriftalpr_constants;

} // namespace

#endif
