/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "thriftalpr_constants.h"

namespace ThriftAlpr {

const thriftalprConstants g_thriftalpr_constants;

thriftalprConstants::thriftalprConstants() {
}

} // namespace

